#!/bin/bash

source tools/_colours

MACHINE_IP="$(docker-machine ip default)"
MACHINE_URL="http://$MACHINE_IP"

echo ""
echo -e "Setting up local development"
echo -e "============================"
echo -e "${BGreen}Web${Color_Off}             $MACHINE_URL:80"
echo -e "${BPurple}BrowserSync${Color_Off}     $MACHINE_URL:3000"
echo -e "${BYellow}BrowserSync UI${Color_Off}  $MACHINE_URL:3001"
echo ""

export X_TERMINAL_COLUMNS=$(tput cols)
export X_TERMINAL_ROWS=$(tput lines)

wercker dev --publish 80 --publish 3000 --publish 3001 "$@"
